version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file: ./client/.env
    depends_on:
      - web
    volumes:
      - /app/node_modules
      - ./client:/app
  web:
    build:
      context: .
      dockerfile: jabme/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./jabme:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jabme
      - POSTGRES_PASSWORD=jabme
      - POSTGRES_DB=jabme_dev
  mailer:
    build:
      context: ./mailer
      dockerfile: Dockerfile
  nginx:
    build:
      context: ./nginx
    ports:
      - 3000:80
    depends_on:
      - web
      - client
volumes:
  postgres_data:
