name: Django CD workflow for heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jabme"
          heroku_email: "sshrivastav_be19@thapar.edu"
