name: "Netlify Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest

    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          build_directory: "./client/build"
          build_command: npm run build
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.API_ID}}
          NETLIFY_DEPLOY_TO_PROD: true
