name: "Netlify Deploy"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 14.16.0
        uses: actions/setup-node@v1
        with:
          node-version: "14.16.0"

      - name: npm install
        run: npm install
        working-directory: "./client"

      - name: npm run build
        run: npm run build --if-present
        working-directory: "./client"

      - name: Deploy Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.API_ID}}
        with:
          args: deploy --dir=./client/build --prod
          secrets: "['NETLIFY_AUTH_TOKEN', 'NETLIFY_SITE_ID']"
